package com.ritmosoft.calculator.calcservice;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
// the RestController that was generated by calc-api is in a sibling package so we have to adjust the scan.
@ComponentScan(basePackages = {"com.ritmosoft.calculator"})
public class CalcServiceApplication {
	public static void main(String[] args) {
		SpringApplication.run(CalcServiceApplication.class, args);
	}
}
