# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Push to master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    container:
      image: maven:3.6-openjdk-11
    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn -B package --file pom.xml
